set_property IOSTANDARD LVCMOS33 [get_ports {a[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports busy]
set_property PACKAGE_PIN M17 [get_ports rst]
set_property PACKAGE_PIN N17 [get_ports start]
set_property PACKAGE_PIN E3 [get_ports clk]
create_clock -add -name clk -period 10.00 -waveform {0 5} [get_ports {clk}];
set_property PACKAGE_PIN H17 [get_ports busy]
set_property PACKAGE_PIN T8 [get_ports {a[0]}]
set_property PACKAGE_PIN U8 [get_ports {a[1]}]
set_property PACKAGE_PIN R16 [get_ports {a[2]}]
set_property PACKAGE_PIN T13 [get_ports {a[3]}]
set_property PACKAGE_PIN H6 [get_ports {a[4]}]
set_property PACKAGE_PIN U12 [get_ports {a[5]}]
set_property PACKAGE_PIN U11 [get_ports {a[6]}]
set_property PACKAGE_PIN V10 [get_ports {a[7]}]
set_property PACKAGE_PIN J15 [get_ports {b[0]}]
set_property PACKAGE_PIN L16 [get_ports {b[1]}]
set_property PACKAGE_PIN M13 [get_ports {b[2]}]
set_property PACKAGE_PIN R15 [get_ports {b[3]}]
set_property PACKAGE_PIN R17 [get_ports {b[4]}]
set_property PACKAGE_PIN T18 [get_ports {b[5]}]
set_property PACKAGE_PIN U18 [get_ports {b[6]}]
set_property PACKAGE_PIN R13 [get_ports {b[7]}]
set_property PACKAGE_PIN J17 [get_ports {an_o[0]}]
set_property PACKAGE_PIN J18 [get_ports {an_o[1]}]
set_property PACKAGE_PIN T9 [get_ports {an_o[2]}]
set_property PACKAGE_PIN J14 [get_ports {an_o[3]}]
set_property PACKAGE_PIN P14 [get_ports {an_o[4]}]
set_property PACKAGE_PIN T14 [get_ports {an_o[5]}]
set_property PACKAGE_PIN K2 [get_ports {an_o[6]}]
set_property PACKAGE_PIN U13 [get_ports {an_o[7]}]
##7 segment display
set_property -dict { PACKAGE_PIN T10   IOSTANDARD LVCMOS33 } [get_ports { CA }]; #IO_L24N_T3_A00_D16_14 Sch=ca
set_property -dict { PACKAGE_PIN R10   IOSTANDARD LVCMOS33 } [get_ports { CB }]; #IO_25_14 Sch=cb
set_property -dict { PACKAGE_PIN K16   IOSTANDARD LVCMOS33 } [get_ports { CC }]; #IO_25_15 Sch=cc
set_property -dict { PACKAGE_PIN K13   IOSTANDARD LVCMOS33 } [get_ports { CD }]; #IO_L17P_T2_A26_15 Sch=cd
set_property -dict { PACKAGE_PIN P15   IOSTANDARD LVCMOS33 } [get_ports { CE }]; #IO_L13P_T2_MRCC_14 Sch=ce
set_property -dict { PACKAGE_PIN T11   IOSTANDARD LVCMOS33 } [get_ports { CF }]; #IO_L19P_T3_A10_D26_14 Sch=cf
set_property -dict { PACKAGE_PIN L18   IOSTANDARD LVCMOS33 } [get_ports { CG }]; #IO_L4P_T0_D04_14 Sch=cg
set_property -dict { PACKAGE_PIN H15   IOSTANDARD LVCMOS33 } [get_ports { DP }]; #IO_L19N_T3_A21_VREF_15 Sch=dp
